---
# See https://pre-commit.com for more information on these settings
repos:
  - repo: https://github.com/polymathrobotics/polymath_code_standard
    rev: v2.6.1
    hooks:
      - id: polymath-general
      - id: polymath-copyright
        args: [--license, Apache-2.0, --copyright-org, 'Polymath Robotics, Inc.', --copyright-year, '2025']
      - id: polymath-cpp
      - id: polymath-ros
      - id: polymath-cmake
      - id: polymath-markdown
      - id: polymath-xml
      - id: polymath-yaml
